### ISSUE TITLE
Times in example GTI file for 1808-369 not in MJD

### ISSUE THREAD

**Issue by outs1der** [adellej/beans#1]
* beans version: unknown
* Python version: 3.8.5
* Operating System: Mac

### Description

Trying to use the gti_checking option

### What I Did

Called beans as recommended in the example, but set gti_checking to 1:
```
gti_checking=1, gtiname='/Users/duncan/python/beans/data/1808_gti.txt', 
  ...:           theta= (0.5, 0.015, 0.2, 2.1, 3.5, 0.108, 0.90, 0.5, 1.4, 11.2), 
  ...:           numburstssim=3, bc=1., threads = 4, restart=False)
Reading in observation data files ...
Observations found: 
 persistent fluxes = [2.437 2.524 2.501 2.536 2.541 2.298 2.084 1.946 1.913 1.853 1.826 1.695
 1.667 1.652 1.511 1.44  1.469 1.465 1.458 1.441 1.361 1.323 1.295 1.259
 1.247 1.184]
 You have chosen gti_checking = 1, so the gti data is st = [-52562.42413039 -52562.36069289 -52562.29476696 -52562.22902622
 -52562.16178085 -52562.09717437 -52562.029929   -52561.9655077
 -52561.37159567 -52561.30585493 -52561.24079706 -52561.17505631
```

examination of the example GTI file suggests those values are already relative to some reference time rather than MJD as expected in the code

**Comment by adellej** [comment]
Thank you for letting me know about this. I have updated the gti file for 1808 in 'data/1808_gti.txt' to contain the gtis in MJD now. Just pull the latest version of the repository and it should replace the 1808_gti file with the new one.
