### ISSUE TITLE
call get_a_b on __init__ and store results with Beans object

### ISSUE THREAD

**Issue by outs1der** [adellej/beans#4]
* beans version: ?
* Python version: 3.8
* Operating System: macOS

### Description

generate_burst_train calls get_a_b, which determines the coefficients for the linear flux interpolation, each time it is run. This step needs to be done only once (e.g. when the Beans object is initialised and the flux measurements read in). The a, b coefficients could then be stored as object attributes and passed to the function

**Comment by adellej** [comment]
Duncan I assume this has been fixed now with your pull request? Okay to close this issue?

**Comment by outs1der** [comment]
resolved by now allowing more than one choice for the interpolation function, determined upon init with the `interp` option (allowed values `spline` and `linear`, latter the default). Interpolation function is an attribute of the `Beans` object (along with the coefficients for both the linear and spline versions, so only need to calculate them once)
